import jax.numpy as jnp
import jax.random
import pytest

import dynamiqs as dq

from ..order import TEST_SHORT
from .stochastic_utils import event_method, run_stochastic_solver

# This module implements the "no-back-action trajectory test" of issue #1079, for
# the four stochastic solver APIs.
#
# We consider a two-qubit system with Hamiltonian
#     H = omega/2 (sigmax x sigmax + sigmay x sigmay),
# a single measured jump operator
#     L = -sigmaz x sigmaz,
# and initial state |01>. The dynamics remain in the odd-parity subspace
# span{|01>, |10>}, on which L acts as the identity. As a consequence, the
# measurement should not introduce any stochastic back-action:
#
# - jump unraveling: the no-click evolution is generated by -iH - L^dag L / 2 =
#   -iH - 1/2, where the measurement part only rescales the norm, and a click
#   applies L, which is a global phase. Single trajectories are thus unaffected by
#   the measurement, whatever the sampled click times.
# - diffusive unraveling: L|psi> = |psi> and <L + L^dag> = 2, so the back-action
#   term (L - <L + L^dag>/2)|psi> dW vanishes identically, as well as the
#   deterministic Ito correction (and similarly for the density matrix terms
#   D[L]rho and Lrho + rho L^dag - <L + L^dag> rho of the SME).
#
# Every single stochastic trajectory must then follow the deterministic analytical
# trajectory
#     |psi(t)> = cos(omega t)|01> - i sin(omega t)|10>,
# which we check at every saved time with the per-trajectory infidelity
#     1 - |<psi_exact(t)|psi_stoch(t)>|^2 ~= 0.
#
# The only remaining error is the deterministic discretization error of the method
# (no statistical error), so the tolerance can be set tightly. Any spurious
# back-action would show up as O(1) trajectory-to-trajectory fluctuations.

# fixed step size for the fixed-step methods
dt = 1e-3


@pytest.mark.run(order=TEST_SHORT)
@pytest.mark.parametrize(
    ('solver', 'method', 'eta', 'theta'),
    [
        ('jssesolve', event_method(), 1.0, 0.0),
        ('jssesolve', dq.method.EulerJump(dt=dt), 1.0, 0.0),
        ('dssesolve', dq.method.EulerMaruyama(dt=dt), 1.0, 0.0),
        ('dssesolve', dq.method.Rouchon1(dt=dt), 1.0, 0.0),
        ('jsmesolve', dq.method.EulerJump(dt=dt), 1.0, 0.0),
        ('jsmesolve', dq.method.EulerJump(dt=dt), 0.4, 0.5),
        ('dsmesolve', dq.method.EulerMaruyama(dt=dt), 1.0, 0.0),
        ('dsmesolve', dq.method.Rouchon1(dt=dt), 0.4, 0.0),
    ],
    ids=[
        'jssesolve-Event',
        'jssesolve-EulerJump',
        'dssesolve-EulerMaruyama',
        'dssesolve-Rouchon1',
        'jsmesolve-EulerJump',
        'jsmesolve-EulerJump-eta0.4-theta0.5',
        'dsmesolve-EulerMaruyama',
        'dsmesolve-Rouchon1-eta0.4',
    ],
)
def test_no_backaction_trajectories(solver, method, eta, theta, atol=1e-4):
    # parameters
    ntrajs = 16
    omega = 2.0

    # solver inputs
    sx, sy, sz = dq.sigmax(), dq.sigmay(), dq.sigmaz()
    H = 0.5 * omega * (dq.tensor(sx, sx) + dq.tensor(sy, sy))
    jump_ops = [-dq.tensor(sz, sz)]
    ket01 = dq.tensor(dq.basis(2, 0), dq.basis(2, 1))
    ket10 = dq.tensor(dq.basis(2, 1), dq.basis(2, 0))
    psi0 = ket01
    tsave = jnp.linspace(0.0, 1.0, 11)
    keys = jax.random.split(jax.random.key(84), num=ntrajs)

    # solve
    result = run_stochastic_solver(
        solver, method, H, jump_ops, psi0, tsave, keys, eta=eta, theta=theta
    )

    # analytical trajectory |psi(t)> = cos(omega t)|01> - i sin(omega t)|10>
    cos, sin = jnp.cos(omega * tsave), jnp.sin(omega * tsave)
    psi_exact = cos[:, None, None] * ket01 - 1j * sin[:, None, None] * ket10

    # compare each trajectory at each saved time to the analytical trajectory
    infidelity = 1 - dq.fidelity(psi_exact, result.states)
    assert jnp.max(infidelity) < atol

    # check that the test is non-trivial for the jump solvers: clicks do occur (the
    # click rate is theta + eta <L^dag L> = theta + eta per trajectory, so we expect
    # about ntrajs clicks in total over [0, 1]), they just have no effect
    if solver in ('jssesolve', 'jsmesolve'):
        assert result.nclicks.sum() > 0
