import jax.numpy as jnp
import jax.random
import pytest

import dynamiqs as dq

from ..order import TEST_LONG
from .stochastic_utils import event_method, run_stochastic_solver

# This module implements the "statistical ensemble test" of issue #1079, for the
# four stochastic solver APIs. The physical problem is the same for all solvers:
# free qubit de-excitation,
#     H = 0, L = sqrt(gamma) sigma-, |psi(0)> = |e>,
# for which both first- and second-order statistics of the stochastic process are
# known analytically. The checked quantity differs between the two unravelings:
#
# - jump unraveling: each trajectory has emitted at most one jump, so the
#   excited-state population of a single trajectory is binary,
#       Pe(t) ~ Bernoulli(p(t)), p(t) = exp(-gamma t),
#   with known mean E[Pe] = p and variance Var[Pe] = p(1 - p).
# - diffusive unraveling: the trajectories are not binary, but the first- and
#   second-order statistics of the continuous measurement record are known
#   analytically (see `test_diffusive_record_statistics` for the derivation).
#
# All statistical tolerances are set to 5 standard errors of the corresponding
# estimator, so each assertion has a false-failure probability of about 1e-6 (the
# bounds are also checked at a smaller ensemble size, verifying that the accuracy
# is consistent with the number of trajectories, i.e. that the error scales as
# 1/sqrt(ntrajs)).


@pytest.mark.run(order=TEST_LONG)
@pytest.mark.parametrize(
    ('solver', 'method'),
    [
        ('jssesolve', event_method()),
        ('jssesolve', dq.method.EulerJump(dt=1e-3)),
        ('jsmesolve', dq.method.EulerJump(dt=1e-3)),
    ],
    ids=['jssesolve-Event', 'jssesolve-EulerJump', 'jsmesolve-EulerJump'],
)
def test_jump_bernoulli_statistics(solver, method):
    r"""Check the Bernoulli statistics of single-trajectory populations for the
    jump unraveling of free qubit de-excitation.

    With $H = 0$, $L = \sqrt\gamma \sigma_-$ and $\psi(0) = \ket e$:

    - the no-click evolution is generated by $-L^\dag L/2 = -\gamma\ket e\bra e/2$,
      of which $\ket e$ is an eigenstate, so the normalized no-click state remains
      exactly $\ket e$, with $P_e = 1$;
    - a click applies $L$, which maps $\ket e$ to $\ket g$, with $P_e = 0$ (and no
      further click can occur).

    Each trajectory is thus excited until a single click occurs at an exponentially
    distributed random time, and the single-trajectory excited population is a
    Bernoulli random variable
    $$
        P_e^{(r)}(t) \in \{0, 1\}, \qquad P_e^{(r)}(t) \sim
        \mathrm{Bernoulli}(p(t)), \qquad p(t) = e^{-\gamma t},
    $$
    with mean $p$ and variance $p(1-p)$. This holds for both the jump SSE and the
    jump SME with perfect detection ($\eta = 1$, $\theta = 0$).

    The test checks, with `ntrajs` trajectories:

    1. each saved population is binary (no spurious diffusion between 0 and 1);
    2. the ensemble mean matches $p(t)$ within 5 standard errors,
       $\mathrm{SE} = \sqrt{p(1-p)/n}$;
    3. the ensemble variance matches $p(1-p)$ within 5 standard errors of the
       sample variance, $\mathrm{SE} = \sqrt{(\mu_4 - \sigma^4)/n}$ with
       $\mu_4 = p(1-p)(1 - 3p(1-p))$ the fourth central moment of the Bernoulli
       distribution (a $25 p(1-p)/n$ term covers the quadratic estimator error at
       points where the leading-order standard error vanishes, e.g. $p = 1/2$);
    4. the click record is consistent with the saved states: $P_e(t) = 1$ exactly
       if no click occurred before $t$;
    5. points 2. and 3. also hold for the first `ntrajs // 4` trajectories with the
       correspondingly larger standard errors, checking that the accuracy is
       consistent with the number of trajectories.

    A wrong decay rate, wrong click statistics, wrong click back-action or spurious
    diffusive back-action would all fail these checks.
    """
    # parameters
    ntrajs = 600
    gamma = 1.0

    # solver inputs
    H = 0.0 * dq.sigmaz()
    jump_ops = [jnp.sqrt(gamma) * dq.sigmam()]
    psi0 = dq.excited()
    tsave = jnp.linspace(0.0, 1.5, 7)
    keys = jax.random.split(jax.random.key(31), num=ntrajs)
    exp_ops = [dq.excited_dm()]

    # solve
    result = run_stochastic_solver(
        solver,
        method,
        H,
        jump_ops,
        psi0,
        tsave,
        keys,
        exp_ops=exp_ops,
        save_states=False,
    )
    pe = result.expects[:, 0, :].real  # (ntrajs, ntsave)

    # 1. each trajectory population is binary (0 or 1 up to the solver tolerance)
    assert jnp.all((pe < 1e-3) | (pe > 1 - 1e-3))
    pe_binary = (pe > 0.5).astype(jnp.float32)

    # Bernoulli parameter at each saved time
    p = jnp.exp(-gamma * tsave)

    # 2., 3. and 5.: first- and second-order statistics at two ensemble sizes, with
    # tolerances set to 5 standard errors of the estimators (false-failure
    # probability ~1e-6 per assertion) + 2e-3 for the O(dt) discretization bias of
    # the click probability
    for n in (ntrajs // 4, ntrajs):
        pe_n = pe_binary[:n]

        # ensemble mean: E[Pe] = p
        mean_tol = 5 * jnp.sqrt(p * (1 - p) / n) + 2e-3
        assert jnp.all(jnp.abs(jnp.mean(pe_n, axis=0) - p) < mean_tol)

        # ensemble variance: Var[Pe] = p(1 - p)
        var = p * (1 - p)
        mu4 = var * (1 - 3 * var)  # fourth central moment of Bernoulli(p)
        var_tol = 5 * jnp.sqrt((mu4 - var**2) / n) + 25 * var / n + 2e-3
        assert jnp.all(jnp.abs(jnp.var(pe_n, axis=0) - var) < var_tol)

    # 4. click/state consistency: Pe(t) = 1 exactly if no click occurred before t
    # (saved times within one time step of the click are excluded, the click time
    # is only resolved at the solver precision)
    tclick = result.clicktimes[:, 0, 0]  # at most one click per trajectory
    tclick = jnp.where(jnp.isnan(tclick), jnp.inf, tclick)
    expected = (tsave[None, :] < tclick[:, None]).astype(jnp.float32)
    resolved = jnp.abs(tsave[None, :] - tclick[:, None]) > 2e-3
    assert jnp.all(jnp.where(resolved, pe_binary == expected, True))


@pytest.mark.run(order=TEST_LONG)
@pytest.mark.parametrize(
    ('solver', 'method', 'eta'),
    [
        ('dssesolve', dq.method.EulerMaruyama(dt=2.5e-3), 1.0),
        ('dsmesolve', dq.method.EulerMaruyama(dt=2.5e-3), 1.0),
        ('dsmesolve', dq.method.EulerMaruyama(dt=2.5e-3), 0.5),
    ],
    ids=[
        'dssesolve-EulerMaruyama',
        'dsmesolve-EulerMaruyama',
        'dsmesolve-EulerMaruyama-eta0.5',
    ],
)
def test_diffusive_record_statistics(solver, method, eta):
    r"""Check the first- and second-order statistics of the measurement record for
    the diffusive unraveling of free qubit de-excitation.

    Same physical problem as `test_jump_bernoulli_statistics`: $H = 0$,
    $L = \sqrt\gamma\sigma_-$, $\psi(0) = \ket e$, but measured by a diffusive
    detector with efficiency $\eta$ ($\eta = 1$ for the SSE). The solvers return
    the time-averaged measurement record over each interval $[t_n, t_{n+1}[$ of
    width $\Delta$,
    $$
        I_n = \frac{Y(t_{n+1}) - Y(t_n)}{\Delta}, \qquad
        \dd Y = \sqrt\eta\,\tr{(L + L^\dag)\rho}\,\dt + \dd W.
    $$

    **First-order statistics.** $\E[\tr{(L+L^\dag)\rho_c(t)}] =
    \tr{(L+L^\dag)\bar\rho(t)} = \sqrt\gamma\braket{\sigma_x}(t) = 0$, since the
    ensemble-averaged state $\bar\rho(t)$ remains diagonal at all times. Hence
    $\E[I_n] = 0$.

    **Second-order statistics.** The variance of $I_n$ is *not* simply the shot
    noise $1/\Delta$: the measurement back-action creates a coherence proportional
    to the noise, which is fed back into the record drift (this is precisely the
    correlation that makes the conditioned states converge to eigenstates). A
    closed-form Ito computation gives it exactly. Writing $m =
    \tr{(L+L^\dag)\rho_c} = \sqrt\gamma\braket{\sigma_x}$ and $P_e =
    \braket{e|\rho_c|e}$, the diffusive SME yields
    $$
        \dd m = -\frac\gamma2 m\,\dt + \sqrt\eta\,(2\gamma P_e - m^2)\,\dd W,
    $$
    so that $f(t) = \E[m(t) Y(t)]$ obeys $f' = -\frac\gamma2 f + 2\sqrt\eta\gamma
    e^{-\gamma t}$ with $f(0) = 0$, i.e. $f(t) = 4\sqrt\eta(e^{-\gamma t/2} -
    e^{-\gamma t})$. From $\dd\E[Y^2] = (1 + 2\sqrt\eta f)\dt$ and the analogous
    computation for the increment over $[t_n, t_{n+1}]$, one finds
    $$
        \mathrm{Var}[I_n] = \frac{1}{\Delta} + \frac{8\eta}{\gamma\Delta^2}
        \left(e^{-\gamma t_n/2} - e^{-\gamma t_{n+1}/2}\right)^2.
    $$
    The same result follows from the output current autocorrelation obtained with
    the quantum regression theorem (see e.g. Wiseman & Milburn, *Quantum
    Measurement and Control*, chapter 4),
    $\E[J(t)J(s)] = \delta(t - s) + 2\eta\gamma e^{-\gamma s}e^{-\gamma(t-s)/2}$
    for $s < t$, integrated over the interval.

    The test checks, with `ntrajs` trajectories:

    1. the ensemble-averaged population follows $e^{-\gamma t}$ within 5 standard
       errors (distribution-free bound $\mathrm{SE} \leq 1/(2\sqrt n)$, since
       $P_e \in [0, 1]$), also at ensemble size `ntrajs // 4`;
    2. the record mean is zero within 5 standard errors,
       $\mathrm{SE} = \sqrt{\mathrm{Var}[I_n]/n}$;
    3. the record variance matches the analytical $\mathrm{Var}[I_n]$ above within
       5 standard errors of the sample variance, $\mathrm{SE} \simeq
       \mathrm{Var}[I_n]\sqrt{2/n}$ (the record is Gaussian-dominated by the
       $\dd W/\Delta$ term, so the Gaussian formula applies to leading order).

    Check 3. fails if the measurement back-action is missing, has the wrong sign or
    the wrong amplitude, or if the record drift $\sqrt\eta\tr{(L+L^\dag)\rho}\dt$
    is incorrect: in all these cases the record variance collapses to the pure shot
    noise $1/\Delta$ (or moves further away), which the test resolves: the
    back-action contribution to the variance of the first interval is more than
    7 standard errors of the estimator.
    """
    # parameters
    ntrajs = 2000
    gamma = 1.0

    # solver inputs
    H = 0.0 * dq.sigmaz()
    jump_ops = [jnp.sqrt(gamma) * dq.sigmam()]
    psi0 = dq.excited()
    tsave = jnp.linspace(0.0, 1.5, 4)
    delta = tsave[1] - tsave[0]  # record time-averaging interval
    keys = jax.random.split(jax.random.key(42), num=ntrajs)
    exp_ops = [dq.excited_dm()]

    # solve
    result = run_stochastic_solver(
        solver,
        method,
        H,
        jump_ops,
        psi0,
        tsave,
        keys,
        exp_ops=exp_ops,
        eta=eta,
        save_states=False,
    )
    pe = result.expects[:, 0, :].real  # (ntrajs, ntsave)
    record = result.measurements[:, 0, :]  # (ntrajs, ntsave - 1)

    # 1. ensemble-averaged population follows the Lindblad decay e^{-gamma t},
    # checked at two ensemble sizes with the distribution-free bound
    # SE <= 1/(2 sqrt(n)) (Pe is [0, 1]-valued), + 5e-3 for the O(dt) weak bias of
    # the Euler-Maruyama method
    p = jnp.exp(-gamma * tsave)
    for n in (ntrajs // 4, ntrajs):
        mean_tol = 5 * 0.5 / jnp.sqrt(n) + 5e-3
        assert jnp.all(jnp.abs(jnp.mean(pe[:n], axis=0) - p) < mean_tol)

    # analytical record statistics for each interval [t_n, t_{n+1}]
    mean_th = jnp.zeros(len(tsave) - 1)
    backaction = (
        8
        * eta
        / (gamma * delta**2)
        * (jnp.exp(-gamma * tsave[:-1] / 2) - jnp.exp(-gamma * tsave[1:] / 2)) ** 2
    )
    var_th = 1 / delta + backaction

    # 2. record mean: E[I_n] = 0
    mean_tol = 5 * jnp.sqrt(var_th / ntrajs)
    assert jnp.all(jnp.abs(jnp.mean(record, axis=0) - mean_th) < mean_tol)

    # 3. record variance: Var[I_n] = 1/Delta + back-action contribution
    var_tol = 5 * var_th * jnp.sqrt(2 / (ntrajs - 1))
    assert jnp.all(jnp.abs(jnp.var(record, axis=0) - var_th) < var_tol)

    # statistical power check: the back-action contribution to the variance of the
    # first interval is resolved at more than 7 standard errors, so check 3. fails
    # if the back-action is missing (record variance 1/Delta)
    assert backaction[0] > 1.5 * var_tol[0]
